// Code generated by tedi; DO NOT EDIT.

package handlers

import (
	"github.com/jstroem/tedi"
	"os"
	"testing"
)

func TestMain(m *testing.M) {
	t := tedi.New(m)

	// TestLabels:
	t.TestLabel("regression")
	t.TestLabel("unit")
	t.TestLabel("integration")

	// Fixtures:
	t.Fixture(fix_gomockController)
	t.Fixture(fix_ToitdocCtrl)
	t.Fixture(fix_RegistryCtrl)
	t.Fixture(fix_Logger)
	t.Fixture(fix_Context)
	t.Fixture(fix_Config)
	t.Fixture(fix_HTTPHandlers)
	t.Fixture(fix_HTTPServer)

	// Tests:
	t.Test("test_HTTPHandlers_Toitdoc", test_HTTPHandlers_Toitdoc, "unit")

	os.Exit(t.Run())
}
